name: Build APK

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build and assemble APK
        run: ./gradlew assembleDebug

      - name: Upload apk as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: |
            app/build/outputs/apk/debug/app-debug.apk